### PR TITLE
Cherry pick taxonomy security from docs restruct

### PR DESCRIPTION
**Pull request by merlin-northern**
Cherry picking Overview/Taxonomy and Overview/Security sections.

### CODE REVIEW

**Comment by mirzak** [comment]
I will get a review of the security document in our separate process and get back to you.

**Comment by merlin-northern** [comment]
> I will get a review of the security document in our separate process and get back to you.

it was reviewed twice I think already. be my guest. should I do something with it to get there?

**Comment by mirzak** [comment]
> it was reviewed twice I think already. be my guest. should I do something with it to get there?

Not by me! :D

But on a serious note, I think it needs some additional grooming that is why I have initiated a new review process on it. You can see a bit more [here](https://docs.google.com/document/d/14j82JVwJGWe_hW2qs19rMWMXuaW9zbqcmofDP4QLJnA/edit). I have restructured it a bit and awaiting further feedback.

I think for now we will respect the process, and away feedback.

**Comment by mirzak** [comment]
Superseded by #1025 and #1026

**Pull request closed without merging**
