### PR TITLE
add documentation tester

### PR DESCRIPTION
**Pull request by GregorioDiStefano**

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
not sure who is interested in this, but @kacf @drewmoseley @estenberg

**Comment by drewmoseley** [comment]
@GregorioDiStefano how is this used?  Do we just run "test_docs.py <blah>/docs.md" and then manually execute the resultant shell script?  Is it only currently supported for "02.Production-installation/docs.md"?

**Comment by GregorioDiStefano** [comment]
@drewmoseley I added a travis file in a previous commit, that's where this script is being used (when ever a PR is made).

How it works is documented in the actually test_docs.py file (as large comment at the very top)

**Comment by GregorioDiStefano** [comment]
@drewmoseley I clarified the tool's usage

**Comment by GregorioDiStefano** [comment]
(sorry, second time I close this PR by accident)

@drewmoseley I updated the documentation inside the tool, let me know if you have anymore questions

**Comment by GregorioDiStefano** [comment]
@drewmoseley How about I just keep the temp file around after the tests are done. 

This way you can jut change it (hostnames) for example, and run the shell script on a droplet somewhere.

**Comment by drewmoseley** [comment]
@GregorioDiStefano that sounds like a reasonable change however after looking further into this I don't think I'll use it much.  If I need a production environment, I'll probably be better off setting it up manually to make sure the networking is done properly to allow access for my target boards.

**Comment by drewmoseley** [comment]
For now I'll merge this and if we decide there is use in making this more generally usable for demos and such we can just make any changes as separate PRs.

**Pull request merged**
