### PR TITLE
Sync hosted branch with master

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Comment by merlin-northern** [comment]
looks good to me

**Review by lluiscampos — CHANGES_REQUESTED** [review]
Missing to run the autoversion tool. See the [docs](https://github.com/mendersoftware/mender-docs/blob/master/README-hosted-maintenance.markdown#3-run-autoversionpy---update-and-commit-the-changes).

Diff:
```
diff --git a/09.Downloads/docs.md b/09.Downloads/docs.md
index 49f11c24..2579681f 100644
--- a/09.Downloads/docs.md
+++ b/09.Downloads/docs.md
@@ -406,14 +406,14 @@ through the package:
 <!--AUTOVERSION: "/mender-monitor_demo_%-1_all.deb"/monitor-client "/mender-monitor/debian/%/"/monitor-client -->
 ```bash
 HOSTED_MENDER_EMAIL=<your.email@example.com>
-curl --fail -u "$HOSTED_MENDER_EMAIL" -O https://downloads.customer.mender.io/content/hosted/mender-monitor/debian/master/mender-monitor_demo_master-1_all.deb
+curl --fail -u "$HOSTED_MENDER_EMAIL" -O https://downloads.customer.mender.io/content/hosted/mender-monitor/debian/1.1.0/mender-monitor_demo_1.1.0-1_all.deb
 ```
 [/ui-tab]
 [ui-tab title="enterprise"]
 
 ```bash
 MENDER_ENTERPRISE_EMAIL=<your.email@example.com>
-curl --fail -u $MENDER_ENTERPRISE_EMAIL -O https://downloads.customer.mender.io/content/on-prem/mender-monitor/debian/master/mender-monitor_demo_master-1_all.deb
+curl --fail -u $MENDER_ENTERPRISE_EMAIL -O https://downloads.customer.mender.io/content/on-prem/mender-monitor/debian/1.1.0/mender-monitor_demo_1.1.0-1_all.deb
 ```
 [/ui-tab]
 [/ui-tabs]
@@ -423,5 +423,5 @@ Then install the package with:
 
 
 ```bash
-dpkg -i mender-monitor_demo_master-1_all.deb
+dpkg -i mender-monitor_demo_1.1.0-1_all.deb
 ```
```

**Comment by lluiscampos** [comment]
> Diff:


Ups. GitHub didn't handle well having markdown inside a markdown code block ;)

**Comment by lluiscampos** [comment]
> Missing to run the autoversion tool. See the [docs](https://github.com/mendersoftware/mender-docs/blob/master/README-hosted-maintenance.markdown#3-run-autoversionpy---update-and-commit-the-changes).

Also note that you will get an erroneous modification of the `mtls-ambassador` version. I'll follow-up on that somehow separately. See https://github.com/mendersoftware/mender-docs/pull/1619/files#r791454582

**Comment by tranchitella** [comment]
@lluiscampos something like this? https://github.com/mendersoftware/mender-docs/pull/1633/commits/75710c719be0acaaa1b9c402f9050595f209314c

**Review by lluiscampos — APPROVED** [review]
yes

**Pull request merged**
