### PR TITLE
fix: Fixed note on how to access getting started example application on virtual device by IP

### PR DESCRIPTION
**Pull request by nickanderson**
Ticket: CE-425
Changelog: None
Signed-off-by: Nick Anderson <nick@cmdln.org>

-------

# External Contributor Checklist

- [ ] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

404.

- [X] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

This change simply adjusts a note to reference the variable that holds the IP instead of the variable that holds the container ID.

### CODE REVIEW

**Comment by lluiscampos** [comment]
@nickanderson Can you please submit your PR to `master` instead? Thanks

**Comment by lluiscampos** [comment]
image

Thanks for reporting :pray: 

@nickanderson The URL in [the template](https://raw.githubusercontent.com/mendersoftware/mender-docs/master/.github/PULL_REQUEST_TEMPLATE.md) is correct. Do you know why GitHub is rendering it wrong in PRs? It used to work when we introduced it.

**Comment by nickanderson** [comment]
> This change simply adjusts a note to reference the variable that holds the IP instead of the variable that holds the container ID.

Sure, here it is. https://github.com/mendersoftware/mender-docs/pull/2430

**Comment by nickanderson** [comment]
> image
> 
> Thanks for reporting 🙏
> 
> @nickanderson The URL in [the template](https://raw.githubusercontent.com/mendersoftware/mender-docs/master/.github/PULL_REQUEST_TEMPLATE.md) is correct. Do you know why GitHub is rendering it wrong in PRs? It used to work when we introduced it.

I do not know, but the `AUTOVERSION` thing seems suspicious.

```
<!-- AUTOVERSION: "/mendertesting/blob/%"/ignore -->
- [ ] Make sure that all commits follow the conventional commit [specification](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for the Mender project.
```
The rendered link is missing `blob/master/` https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md

I poked through a couple other PRs to this repo and the link seems to work in other places. So, that is making me think that maybe this magic AUTOVERSION thing is a github web ui special. I didn't create my PR via the web ui, I created it from inside emacs with magit. So, next time I PR here I will try to remember to do it with the web client and see if it's still broken.

But, maybe

**Pull request closed without merging**
