### PR TITLE
preauth improvements of MEN-1900 and MEN-1901

### PR DESCRIPTION
**Pull request by estenberg**

### CODE REVIEW

**Comment by estenberg** [comment]
ping @mchalski

**Comment by drewmoseley** [comment]
@estenberg is this still relevant? Both of the JIRA tickets referenced above are closed so it seems like this is ready to be merged.  I don't know the details as well as @mchalski but it looks right to me.

Is this only relevant for the master branch?

**Comment by estenberg** [comment]
Yes, I am waiting for @mchalski or @kjaskiewiczz for approval
And indeed, I believe this is only for master / 1.7.

**Comment by drewmoseley** [comment]
@mchalski @kjaskiewiczz please review

**Comment by estenberg** [comment]
Closing, it is now part of PR https://github.com/mendersoftware/mender-docs/pull/579

**Pull request closed without merging**
