### PR TITLE
Use fully qualified branch for git log command.

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@GregorioDiStefano @kacf does this look right?

**Comment by estenberg** [comment]
Note that this would need to be updated every release (like now we are about to release 1.2.2). If we want this then we definitely need some kind of automation here.

**Comment by drewmoseley** [comment]
True but I'm more worried that we are inconsistent between the branches.  I can change this to use the branch name which would not require updating.  ie "git log origin/1.2.x..HEAD"

Is that a preferred change?

**Comment by estenberg** [comment]
Makes sense to me. :)

**Comment by drewmoseley** [comment]
OK.  I updated all the branches and PRs so that the git clone command uses the proper tag but the git log command uses the fully qualified branch name.  That means for point releases that we won't need to update the text of the git log command.

**Comment by kacf** [comment]
Automation is on its way, don't worry about that, this is a drop in the ocean compared to all the other version replacements. But what is most correct from a user perspective? I think the tag is the most correct, and this is indeed what I added to the 1.3.x branch. This also saves us from having to specify the upstream name, because it's not guaranteed to always be `origin`.

Do you agree?

**Comment by estenberg** [comment]
sure, sounds good.

**Comment by drewmoseley** [comment]
Updated.  Once the CI tests complete I'll merge this and the other branches.

**Pull request merged**
