### PR TITLE
MEN-547: Write verification checklist for correct U-Boot integration.

### PR DESCRIPTION
**Pull request by kacf**
Signed-off-by: Kristian Amlie <kristian.amlie@mender.io>

### CODE REVIEW

**Comment by kacf** [comment]
@csimmonds: Perhaps you could verify that this looks sane to your eyes?

I plan to follow up with a PR with a few entries of the type "What if step X fails?"

**Comment by csimmonds** [comment]
@kacf: It's quite an intricate series of steps. I feel that it needs a bit more context at the beginning ("we are going to create two different images and verify that mender can update from one to the other"...) and to explain what each step is for *before* giving the sequence of commands

**Comment by kacf** [comment]
Good idea, I'll add that.

**Comment by kacf** [comment]
@csimmonds: I have updated with more contextual info, check the last commit!

**Pull request merged**
