### PR TITLE
Docs: Adds session token usage for CLI and API

### PR DESCRIPTION
**Pull request by jthacker**
Changelog: None
Ticket: None

### Description

Adds a section to server integration docs that describes how to use session tokens for CLI and API uses cases.
This is helpful to know for users of SSO.

### CODE REVIEW

**Review by MuchoLucho — CHANGES_REQUESTED** [review]
Hello Jon,

Thanks for the PR, just two comments:

1. Can you sign off the commit? Just use `git commit --signoff` when creating the commit.

It is used to say that you certify that you have created the patch in question, or that you certify that to the best of your knowledge, it was created under an appropriate open-source license, or that it has been provided to you by someone else under those terms.

2. The session has the same validity span than a JWT, so it will depend if the "Keep the session active" was flagged or not.

In this case:

* case of inactivity - 15min
* with "keep me signed in" - 24h

Thanks for your contribution.
Luis

**Comment by jthacker** [comment]
Sure thing @lluiscampos, I did this in the UI originally and I thought github had signed it but I guess not. 
I updated the section on validity span based on your comment. Let me know if that looks right to you.

**Comment by jthacker** [comment]
@lluiscampos I think all feedback has now been addressed

**Comment by lluiscampos** [comment]
> @lluiscampos I think all feedback has now been addressed

I think you meant to ping @MuchoLucho :smiley:

**Pull request merged**
