### PR TITLE
New 'Get started" section

### PR DESCRIPTION
**Pull request by mirzak**
Rendering available here:

http://13.53.78.221:8080/foo

### CODE REVIEW

**Comment by mirzak** [comment]
The error in CI is known, and seems to be a conflict with how grav and our link checker works and is a false positive.

```
 01.Get-started/02.Deploy-an-application-update/docs.md
     63:1-63:60  warning  Link to unknown heading: `step-1-create-a-deployment`. Did you mean `step-1---create-a-deployment`  missing-heading  remark-validate-links
   107:1-107:60  warning  Link to unknown heading: `step-1-create-a-deployment`. Did you mean `step-1---create-a-deployment`  missing-heading  remark-validate-links
```

`step-1-create-a-deployment` - does generate a valid link when rendered
`step-1---create-a-deployment` - does remove the error from the link checker but does not work when the site is rendered.

@oleorhagen, is looking in to this.

**Comment by oleorhagen** [comment]
> The error in CI is known, and seems to be a conflict with how grav and our link checker works and is a false positive.
> 
> ```
>  01.Get-started/02.Deploy-an-application-update/docs.md
>      63:1-63:60  warning  Link to unknown heading: `step-1-create-a-deployment`. Did you mean `step-1---create-a-deployment`  missing-heading  remark-validate-links
>    107:1-107:60  warning  Link to unknown heading: `step-1-create-a-deployment`. Did you mean `step-1---create-a-deployment`  missing-heading  remark-validate-links
> ```
> 
> `step-1-create-a-deployment` - does generate a valid link when rendered
> `step-1---create-a-deployment` - does remove the error from the link checker but does not work when the site is rendered.
> 
> @oleorhagen, is looking in to this.

I'm sorry it took so long, I was having issues rendering the site to see if what I was doing worked.
The issue is that the dash in the section header needs to be escaped, so:
```
#step-1-\--create-a-deployment
```
Seems to work :+1:

**Comment by mirzak** [comment]
Hmm, this didn't work me for.

```diff
diff --git a/01.Get-started/02.Deploy-an-application-update/docs.md b/01.Get-started/02.Deploy-an-application-update/docs.md
index 8cb542e..5c1d80a 100644
--- a/01.Get-started/02.Deploy-an-application-update/docs.md
+++ b/01.Get-started/02.Deploy-an-application-update/docs.md
@@ -60,7 +60,7 @@ using Mender!
 ## Step 2 - Modify the application
 
 The UI tooltips should now take you through modifying the web page you saw in
-[Step 1 - Create a Deployment](#step-1-create-a-deployment). Follow the
+[Step 1 - Create a Deployment](#step-1-\--create-a-deployment). Follow the
 instructions showed on the pop-up and click the **NEXT** button when done.
 
 ![Upload web page](Image_13.png)
@@ -104,7 +104,7 @@ Fill out the required fields and click the **UPLOAD** button.
 You now have a new Artifact under the **Releases** tab. Use the new Artifact
 to create a deployment by clicking **CREATE DEPLOYMENT WITH THIS RELEASE** and
 click trough the deployment wizard, similarly to what you did in
-[Step 1 - Create a Deployment](#step-1-create-a-deployment).
+[Step 1 - Create a Deployment](#step-1-\--create-a-deployment).
 
 ![Upload web page](Image_19.png)

```

I think I did the changes correct, but the rendered link does not work. That `\` ends up in the link,

http://localhost:8080/foo/get-started/deploy-an-application-update#step-1-\--create-a-deployment

**Comment by oleorhagen** [comment]
```
diff --git a/01.Get-started/02.Deploy-an-application-update/docs.md b/01.Get-started/02.Deploy-an-application-update/docs.md
index 8cb542e..35df786 100644
--- a/01.Get-started/02.Deploy-an-application-update/docs.md
+++ b/01.Get-started/02.Deploy-an-application-update/docs.md
@@ -104,7 +104,7 @@ Fill out the required fields and click the **UPLOAD** button.
 You now have a new Artifact under the **Releases** tab. Use the new Artifact
 to create a deployment by clicking **CREATE DEPLOYMENT WITH THIS RELEASE** and
 click trough the deployment wizard, similarly to what you did in
-[Step 1 - Create a Deployment](#step-1-create-a-deployment).
+[Step 1 - Create a Deployment](#step-1-\--create-a-deployment).
 
 ![Upload web page](Image_19.png)
 
```
http://13.53.78.221:8090/foo/get-started/deploy-an-application-update#step-1-create-a-deployment

**Comment by mirzak** [comment]
Are we using different browsers? Can you try it on this location:

http://13.53.78.221:8080/foo/get-started/deploy-an-application-update

**Comment by oleorhagen** [comment]
> Are we using different browsers? Can you try it on this location:
> 
> http://13.53.78.221:8080/foo/get-started/deploy-an-application-update

You are right @mirzak, and I am wrong (as usual). 

It seems that it is the link-checker which is wrong. 

It was kinda hard to figure out who or what was at fault here, or how to work around it.

I had a look at the markdown specification from github: https://github.github.com/gfm/#link-destination
The implementation on github: https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb
But the clearest explanation is here I think: https://docs.gitlab.com/ee/user/markdown.html#header-ids-and-links

> 
>   1.  All text is converted to lowercase.
>    2. All non-word text (such as punctuation or HTML) is removed.
>    3. All spaces are converted to hyphens.
>   4. Two or more hyphens in a row are converted to one.
>    5. If a header with the same ID has already been generated, a unique incrementing number is appended, starting at 1. 

Where (4) is of our interest it seems.

Which means I'm gonna spend the next minutes trying to debug `node.js` code (go me).

**Comment by oleorhagen** [comment]
Okay, done a little bit more digging. And the form which fails here, is valid in both Gitlab and Github. It is just Grav which does not play nice with it :/

**Pull request merged**
