### PR TITLE
Fix: mender-artifact cp requires an explicit '-' to read from stdin

### PR DESCRIPTION
**Pull request by oleorhagen**
This was discovered in accordance with onboarding of the bbb

Changelog: None

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@oleorhagen does this need to be cherry picked to older branches?

**Comment by oleorhagen** [comment]
Yes, I will. There are a few more commits coming on top of this tomorrow though first ;)

**Comment by oleorhagen** [comment]
Done

**Comment by oleorhagen** [comment]
Cherry of 2.3.x: https://github.com/mendersoftware/mender-docs/pull/895
Cherry of 2.2.x: https://github.com/mendersoftware/mender-docs/pull/896 (without the 'cp -' amendment, since mender-artifact 2.3.x does not have it)

**Comment by lluiscampos** [comment]
> Cherry of 2.2.x: #896 (without the 'cp -' amendment, since mender-artifact 2.3.x does not have it)

Sorry, I had a typo in my original message (edited now). Mender release 2.2.x uses mender-artifact 3.2.x which does have the `-` amendment, so you need the commit there also. Actually, `mender-artifact` 2.x is really old (Mender 1.x)

**Comment by oleorhagen** [comment]
> > Cherry of 2.2.x: #896 (without the 'cp -' amendment, since mender-artifact 2.3.x does not have it)
> 
> Sorry, I had a typo in my original message (edited now). Mender release 2.2.x uses mender-artifact 3.2.x which does have the `-` amendment, so you need the commit there also. Actually, `mender-artifact` 2.x is really old (Mender 1.x)

All fixed now. Merging.

**Pull request merged**
