### PR TITLE
docs: Replace OS codenames with numbers

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Review by mzedel — APPROVED** [review]
I approve this ~message~ change!

**Comment by nickanderson** [comment]
I always struggle to recall what number a codename is related to, so this would be a +1 in my book. I might however suggest having both, e.g. `Debian 12 (Bookworm)`

**Comment by lluiscampos** [comment]
> I always struggle to recall what number a codename is related to, so this would be a +1 in my book. I might however suggest having both, e.g. `Debian 12 (Bookworm)`

Thanks for your feedback @nickanderson.

There is however an extra hidden motivation in doing this change: to have our tabs render in one line! See how they look right now:

image

So having both the codename and the number would defeat this.

**Comment by nickanderson** [comment]
> So having both the codename and the number would defeat this.

Screen space is the toughest final boss

**Comment by lluiscampos** [comment]
@mender-test-bot cherry-pick to:
* hosted
* 3.7.x

**Pull request merged**
