### PR TITLE
Add Mac OS path for SD card

### PR DESCRIPTION
**Pull request by estenberg**
FuP to https://github.com/mendersoftware/mender-docs/pull/1571

### CODE REVIEW

**Comment by estenberg** [comment]
Quick review please @mzedel ? I can't merge until reviewed. :)

**Review by mzedel — APPROVED** [review]

**Comment by estenberg** [comment]
I think the tests failed due to infra / timeout.

@lluiscampos  Can I re-trigger test run somehow? Sorry I'm not too familiar with the CI setup.

**Comment by mzedel** [comment]
@estenberg I re-ran the failed test job but it failed again... I suspect you need to rebase to include a fix for the tests...

**Comment by estenberg** [comment]
Thanks @mzedel , rebased :crossed_fingers:

**Pull request merged**
