### PR TITLE
chore: ensure canonical links don't point to Hosted version for Serve…

### PR DESCRIPTION
**Pull request by michaelntech**
…r Installation pages

Ticket: MEN-5877
Changelog: None

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by michaelatmender** [comment]
Cherry pick to 3.3.x also

**Review by mzedel — APPROVED** [review]
lgtm, although that might now be something that we have to add to the release checklist instead of the sitemap generation 😢

**Comment by lluiscampos** [comment]
@michaelatmender This needs to be ported to `master` with an AUTOVERSION tag so that we can automatically update the versions when we branch out future releases (so no need to an extra release checklist item, Manuel).

I can take care of it. But please answer me the following:
* How should it work on master (aka development docs)? Should it be like `canonical: /development/server-installation/overview` ?
* How should it work on hosted (aka default docs)? Just removing these lines?

**Comment by michaelatmender** [comment]
Thanks @lluiscampos!
1) It should be as you described on master, but I didn't include it because development docs should not be indexed by search engines - so I added only on the latest 2 versions. If we change master too then it should be how you wrote it!
2) Exactly :)

**Comment by lluiscampos** [comment]
@mender-test-bot cherry-pick to:
* 3.3.x

**Pull request merged**
