### PR TITLE
fix mender-standalone download link

### PR DESCRIPTION
**Pull request by GregorioDiStefano**

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
@estenberg

**Comment by GregorioDiStefano** [comment]
oops, fixed the link.

**Comment by estenberg** [comment]
I get access denied on https://doyabzhx7xw8o.cloudfront.net/master/mender-standalone.tar.gz

**Comment by GregorioDiStefano** [comment]
yup, because the file doesn't exist, I'm build master now, should be done in 5-10 minutes.

**Comment by GregorioDiStefano** [comment]
fixed

**Pull request merged**
