### PR TITLE
specify menderproduction project when creating a user

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
@drewmoseley there seems to be a mistake in the documentation, if you are setting up a production environment, the "menderproduction" project must be set.

**Comment by drewmoseley** [comment]
@GregorioDiStefano I think I fixed this differently in the master branch but using the run script.  See https://github.com/mendersoftware/mender-docs/pull/259.  (Evidently I neglected to cherry pick it to 1.2)

I _think_ using the run script is more flexible as we can modify that without needing to update the docs.  Thoughts?

**Comment by GregorioDiStefano** [comment]
@drewmoseley makes perfect sense! should I just close this then?

**Comment by drewmoseley** [comment]
Can you first confirm that my change resolves the issue you are seeing?  I'll create PRs against the other branches once you do and we can close this one.

**Comment by GregorioDiStefano** [comment]
Yup, your fix looks correct!

**Pull request closed without merging**
