### PR TITLE
M Fixed link

### PR DESCRIPTION
**Pull request by antonkraft**
# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by lluiscampos** [comment]
Good catch @antonkraft, thanks!

The change itself is good, but we need few formalities to get it merged. It needs to be submitted to master branch instead (it is a bit confusing, but once it lands in master we'll propagate it to the rest of the active branches). In addition, you need to follow the conventional commit specification and sign your commit (see `External Contributor Checklist` in this pull request).

Your fix also surfaced a limitation in our CI script that I will try to fix meanwhile.

Thanks.

**Comment by antonkraft** [comment]
Hello Luis, sorry I did not know anything about that. I merely clicked on Edit on docs.mender.io and just did the offered Mergerequest. I suppose I redo manually the request onto master with a signed commit and close this one ?

**Comment by lluiscampos** [comment]
@antonkraft Yes, the easiest is to close the PR and manually re-create from `master`. If this is too troublesome for you I can take over :+1:

**Comment by antonkraft** [comment]
That would be nice and make this almost as easy as editing something on Wikipedia.

**Pull request closed without merging**
