### PR TITLE
1.4.x

### PR DESCRIPTION
**Pull request by drewmoseley**

### CODE REVIEW

**Comment by drewmoseley** [comment]
@estenberg is this branch open for check-in now?

@oleorhagen note that I had to cherry-pick the reboot hardening commit here to get the others to apply cleanly.  Is that documentation relevant for the 1.4.x branch?

**Comment by oleorhagen** [comment]
No, it did not make the release

**Comment by drewmoseley** [comment]
OK.  Thanks for confirming.  I've rebased this and dropped the hardening docs.

**Comment by estenberg** [comment]
I think you can commit to this branch, yes.

**Pull request merged**
