### PR TITLE
Add extra configuration to make the image work on the RPi

### PR DESCRIPTION
**Pull request by jerbob92**

### CODE REVIEW

**Comment by drewmoseley** [comment]
This change should not be needed on Rocko or newer.
@kacf since this repo uses a different branching scheme than the Yocto ones, should we list both styles in the docs with a comment about the Yocto version for each set?

**Comment by jerbob92** [comment]
@drewmoseley But where in the docs are you talking about Rocko?
I'd suggest adding this to the current docs with the comment:
```
# Lines below not needed for Yocto Rocko (2.4) or newer.
```

It really took me a long time to figure out why the system wasn't booting.

**Comment by kacf** [comment]
> since this repo uses a different branching scheme than the Yocto ones, should we list both styles in the docs with a comment about the Yocto version for each set?

Yes, I suppose that's the most sensible.

> But where in the docs are you talking about Rocko?

We haven't branched yet, so indeed we haven't mentioned rocko so far. But we will. In the meantime it's no problem to start referring to it.

**Comment by jerbob92** [comment]
@kacf should I change the PR to mention Rocko?

**Comment by kacf** [comment]
Yes, please!

**Comment by jerbob92** [comment]
Done

**Comment by kacf** [comment]
Thanks!

Cherry-picked to 1.2.x and 1.3.x as well.

**Comment by estenberg** [comment]
Thanks for the contribution @jerbob92 !

**Pull request merged**
