### PR TITLE
chore: Update OS licenses for new release

### PR DESCRIPTION
**Pull request by lluiscampos**
These cover the licenses used in Mender Client 5.x, Mender Gateway 2.x and all the rest of the updated tools.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Reviewers,

Note that this time we remove much more that we add because the OS licenses used in Mender Server and Mender Server Enterprise are moved (duplicated, for now) into separate sections.

**Comment by kjaskiewiczz** [comment]
+548 −20,172
We are removing most of the licenses, because we excluded licenses coming from mender-server, right?

**Review by vpodzime — COMMENTED** [review]
Why is there such a huge diff? That looks suspicious. @lluiscampos can you please elaborate a bit more than the commit message on what exactly is going on here?

**Comment by lluiscampos** [comment]
> Why is there such a huge diff? That looks suspicious. @lluiscampos can you please elaborate a bit more than the commit message on what exactly is going on here?

Please [see above](https://github.com/mendersoftware/mender-docs/pull/2512#issuecomment-2551296728).

**Comment by lluiscampos** [comment]
> Please [see above](https://github.com/mendersoftware/mender-docs/pull/2512#issuecomment-2551296728).

And [this PR](https://github.com/mendersoftware/mender-docs/pull/2496).

**Comment by vpodzime** [comment]
> Please [see above](https://github.com/mendersoftware/mender-docs/pull/2512#issuecomment-2551296728).

Oh, I see. I wish it was in the commit message.

**Pull request merged**
