### PR TITLE
Update docs.md

### PR DESCRIPTION
**Pull request by MuchoLucho**
Removing extra parenthesis

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Review by tranchitella — APPROVED** [review]

**Comment by MuchoLucho** [comment]
@tranchitella I already signed off the commit. Thanks for the heads up

**Comment by tranchitella** [comment]
@MuchoLucho Nope, still not correct. You should squash your commits into one, and use both `-s` and `-S` (signing with gpg and adding the Sign-off keyword in the commit message).

**Comment by tranchitella** [comment]
@MuchoLucho ping

**Comment by tranchitella** [comment]
Applied your fix to my PR (https://github.com/mendersoftware/mender-docs/pull/1542)

**Pull request closed without merging**
