### PR TITLE
Replace index with number to match what the code is actually looking for

### PR DESCRIPTION
**Pull request by robertalexa**
During implementation at my end, i've discovered some discrepancies between some variables referenced in the docs and what mender-convert actually looks for.

PS: there may be other discrepancies but the ones submitted are the only ones i have looked into, for now.

### CODE REVIEW

**Review by lluiscampos — CHANGES_REQUESTED** [review]
@robertalexa Good catch! This was changed [long time ago](https://github.com/mendersoftware/mender-convert/pull/160) but it went unnoticed until now. Thank you very much :rocket:

The change is good, but there is one formality to take care of: the commit needs to be signed. Check the [contribution](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) guide.

Once you amend your commit with the signature I'll merge it and port it to all relevant branches.

**Comment by robertalexa** [comment]
@lluiscampos All done now. Commit message does not contain a note about signing, but if you check the Verified mark you can see it is signed with my personal key rather than the previously used Github (i have submitted the PR via the website itself)

Hope this is what you were after!

**Review by lluiscampos — APPROVED** [review]
@robertalexa Yes, it looks good now!

**Comment by lluiscampos** [comment]
@mender-test-bot cherry-pick to:
* master
* 3.5.x
* 3.3.x

**Pull request merged**
