### PR TITLE
Also mask/disable mender client

### PR DESCRIPTION
**Pull request by mifi**
# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

I believe we also need to disable the mender client, so it doesn't auto restart on the next boot? Or maybe I'm missing something, in such case maybe we should improve the documentation.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Hi @mifi and thank you for your contribution.

It looks good to me :+1: 

Some formalities required. You need to sign your commit as instructed in our [guidelines](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md). You have tried by commenting on the commit, but what you need to do is to add the signature as part of the commit body.

For that:
* fork the repository
* checkout it locally
* modify (add the space)
* `git commit -s -a`
* push and launch PR

I am sorry, but the GitHub UI interface does not allow for adding the signature nor amending commits, so unfortunately you need to use your local Git.

If you don't want to do that I can submit the change on your name.

**Comment by mifi** [comment]
Hi! That's a pity as it makes it harder for people to easily contribute and improve the documentation. Anyways I signed the commit fro mthe command line now. hope it works!

**Comment by lluiscampos** [comment]
> Hi! That's a pity as it makes it harder for people to easily contribute and improve the documentation. Anyways I signed the commit fro mthe command line now. hope it works!

I know :weary: But the signature is important for our open source license model, so there is no other way around that asking the user to "do something manually" on their machine ;)

Thank you!

**Comment by mifi** [comment]
Maybe it could be worked around by a github action that auto-signs the commits 🙈

**Comment by lluiscampos** [comment]
> Maybe it could be worked around by a github action that auto-signs the commits see_no_evil

But that is the point, we **cannot** sign contributor's commits... that defeats the license agreement.

**Pull request merged**
