### PR TITLE
Move 03.Integration-APIs to 03.Management-APIs

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
@eysteins @michaelatmender

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
We will wait for stable to be updated to master, before proceeding with this

**Comment by estenberg** [comment]
Looks good, just run a deadlinkcheck.com after you merge to prod.

**Comment by maciejmrowiec** [comment]
ping!?

**Comment by maciejmrowiec** [comment]
btw this file also needs changes: https://github.com/mendersoftware/mender-docs/blob/master/200.APIs/01.Overview/docs.md

**Comment by estenberg** [comment]
@GregorioDiStefano are you merging this when ready?

**Comment by GregorioDiStefano** [comment]
yes, but we need to update current stable to master, and we arent there yet.

**Pull request merged**
