### PR TITLE
Bump the RaspiOS version

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
Merge as part of the release

**Review by lluiscampos — COMMENTED** [review]
I am getting `AccessDenied` on these.

**Comment by oleorhagen** [comment]
> I am getting `AccessDenied` on these.

Yes, because they don't exist yet :smile_cat:

**Comment by oleorhagen** [comment]
Maybe a better intermediate solution be to bump them to `2.3.2` client version actually :thinking:

**Comment by oleorhagen** [comment]
But now they're very close to existing:
https://gitlab.com/Northern.tech/Mender/mender-convert/-/pipelines/289136114
:smiley:

**Pull request merged**
