### PR TITLE
Merge master into hosted

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Comment by mirzak** [comment]
This does not look correct to me, there are a lot of sections in here that are removed in master. How exactly did you create this?

I tested doing a merge locally and something like this produces what seems to be correct:

```
git merge -X theirs origin/master
git rm 03.Devices/03.Debian-family/docs.md 03.Devices/10.Update-Modules/docs.md
git rm 04.Artifacts/25.Modifying-a-Mender-Artifact/docs.md 05.Client-configuration/02.Cross-compiling/docs.md
git merge --continue
```

**Comment by mirzak** [comment]
Looping in @lluiscampos. I am not sure how the stable versions have been handled in the past on the `hosted` branch.

**Comment by lluiscampos** [comment]
> Looping in @lluiscampos. I am not sure how the stable versions have been handled in the past on the `hosted` branch.

@mirzak Your merge recipe looks correct.

After you commit the merge, however, you need to rerun the `autoversion` tool again to replace any new introduced version reference or the ones that by conflicts resolution have been wiped out.

I will launch a new PR in few minutes.

**Comment by lluiscampos** [comment]
> I will launch a new PR in few minutes.

See #1122

**Pull request closed without merging**
