### PR TITLE
Include missing volumes

### PR DESCRIPTION
**Pull request by GregorioDiStefano**

### CODE REVIEW

**Comment by drewmoseley** [comment]
@GregorioDiStefano any idea why this failed the Travis tests?

**Comment by GregorioDiStefano** [comment]
"Could not find .travis.yml, using standard configuration."
No idea why, but I did use the GitHub editor.

I'll fix this when I'm back in the office

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano is this cherry-pick from master ?

**Comment by maciejmrowiec** [comment]
then you missed `-x` ;)

**Comment by GregorioDiStefano** [comment]
Sorry, misread that!

The actual fix for this is to cherry-pick the documentation testing stuff from master, and it's been done, with -x argument :)

**Comment by drewmoseley** [comment]
@GregorioDiStefano is this ready for merge now?  It looks ok to me.

@maciejmrowiec any other concerns?

**Comment by GregorioDiStefano** [comment]
@drewmoseley yup! It's ready

**Pull request merged**
