### PR TITLE
Documentation restructuring bring master

### PR DESCRIPTION
**Pull request by lluiscampos**
The intention of the merge is to bring CI improvements.

Resolving the conflicts to bring only relevant changes: minor wording in
some already ported documents.

### CODE REVIEW

**Comment by lluiscampos** [comment]
@oleorhagen I don't understand, however, where the following files are coming from, as I don't see them in `master` nor in `
- 02.Overview/05.Deployments/docs.md
- 02.Overview/06.Standalone-deployments/docs.md

What did I mess up in the merge?

**Comment by oleorhagen** [comment]
> @oleorhagen I don't understand, however, where the following files are coming from, as I don't see them in `master` nor in `
> 
>     * 02.Overview/05.Deployments/docs.md
> 
>     * 02.Overview/06.Standalone-deployments/docs.md
> 
> 
> What did I mess up in the merge?

That is curious indeed! :p

I don't have a good explanation for it, but it seems that it has changed the top-level directory to `Overview` from master, where it was previously `Architecture`. The rest seems to be from master. If that makes sense?

**Comment by oleorhagen** [comment]
Also, thank you for this! 

:medal_military:

**Comment by lluiscampos** [comment]
> > 
> > What did I mess up in the merge?
> 
> That is curious indeed! :p
> 
> I don't have a good explanation for it, but it seems that it has changed the top-level directory to `Overview` from master, where it was previously `Architecture`. The rest seems to be from master. If that makes sense?

But there is no top-level Overview in master... right? I still don't get it.

I will delete them from the merge, and they will need to be ported with their corresponding JIRA task as we are doing for all other files.

**Comment by oleorhagen** [comment]
> But there is no top-level Overview in master... right? I still don't get it.
> 
> I will delete them from the merge, and they will need to be ported with their corresponding JIRA task as we are doing for all other files.

Sure.

What I meant is that for some reason it looks like:

| master | => | documentation-restructuring |
| :---: | :----: | :----: | 
| /02.Architecture/05.Deployments/docs.md | | /02.Overvies/05.Deployments/docs.md |

has happened for some reason. I got no further observations to contribute :p

**Comment by lluiscampos** [comment]
> What I meant is that for some reason it looks like:

Got your point now, thanks.

Removed the files and updated the PR. I will merge after CI.

**Pull request merged**
