### PR TITLE
Mender daemon now autostarts: Remove explicit Mender daemon setting.

### PR DESCRIPTION
**Pull request by kacf**
Signed-off-by: Kristian Amlie <kristian.amlie@mender.io>

### CODE REVIEW

**Comment by kacf** [comment]
Merge together with https://github.com/mendersoftware/meta-mender/pull/204.

**Comment by eysteins** [comment]
Does this affect stable or only master? If not I will wait until we have moved stable.

**Comment by kacf** [comment]
Only master.

**Comment by kacf** [comment]
Ok, merge this when stable is updated.

**Comment by kacf** [comment]
Appears to be covered in master already.

**Pull request closed without merging**
