### PR TITLE
Use https://localhost to access demo environment, it is allowed

### PR DESCRIPTION
**Pull request by drewmoseley**
after https://github.com/mendersoftware/integration/pull/322

Signed-off-by: Eystein Måløy Stenberg <eystein@mender.io>
(cherry picked from commit d4b58b9fc38f8367912d911f020f71e274634f42)

### CODE REVIEW

**Comment by drewmoseley** [comment]
@estenberg is this appropriate for 1.2?

**Comment by kacf** [comment]
Hmm, will that work? I recall that I explicitly had to use the domain name in order for the server filter to accept me (`ALLOWED_HOSTS` or something).

**Comment by drewmoseley** [comment]
@kacf we definitely did for a while but I thought it had been fixed.  @estenberg put the docs patch in master and I seem to recall that the actual fix also went into 1.2.  Let me dig a bit.

**Comment by drewmoseley** [comment]
Yeah, the original master PR is here: https://github.com/mendersoftware/integration/pull/322 and @estenberg commented that it was cherry picked to 1.2 here: https://github.com/mendersoftware/integration/commit/1dc2db336b2b7bce2085dce8c135711986e0555a

**Comment by GregorioDiStefano** [comment]
Tested locally, worked.

**Comment by drewmoseley** [comment]
Thanks for checking

**Pull request merged**
