### PR TITLE
Updated configuration of local.conf file to add kernel-devicetree

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
@kacf @eysteins

### CODE REVIEW

**Comment by eysteins** [comment]
I don't know, this one is for @kacf :)

**Comment by bboozzoo** [comment]
I suppose you're trying to replicate this patch:
https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/meta-yocto-bsp/conf/machine/beaglebone.conf?id=3a73fe0efcb7aeefcca7011bba887caad03d4d03

So for krogoth you'll likely need to add the following line:
`IMAGE_INSTALL_append_beaglebone = " kernel-devicetree kernel-image-zimage"`

Morty & master branches don't need any appends.

**Comment by kacf** [comment]
Not needed, I plan to fix this permanently in the layer.

**Comment by kacf** [comment]
https://github.com/mendersoftware/meta-mender/pull/167

**Pull request closed without merging**
