### PR TITLE
06.Administration/02.Production-installation: configure allowed gatew…

### PR DESCRIPTION
**Pull request by mchalski**
…ay hosts

notes on how to define the gateway's host whitelist for the purpose
of preventing host header injection attacks.

Issues: MEN-1262

Changelog: None

Signed-off-by: mchalczynski <marcin.chalczynski@rndity.com>

### CODE REVIEW

**Comment by drewmoseley** [comment]
Looks ok to me.  The only nitpick I have is the changelog title line wraps funny.  @estenberg how picky are we being about changelog formatting?

**Comment by drewmoseley** [comment]
@estenberg any thoughts on the nitpick here?

**Comment by estenberg** [comment]
I do not believe changelog title wrapping has been an issue, so I don't know about that.

**Comment by drewmoseley** [comment]
Sounds good.  Merging.

Acked-by: Drew Moseley \<drew.moseley@mender.io\>

**Pull request merged**
