### PR TITLE
minio limits passwords to 20 characters

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
https://github.com/minio/minio/blob/master/cmd/credential.go#L29

**Comment by GregorioDiStefano** [comment]
@maciejmrowiec

**Comment by maciejmrowiec** [comment]
nice, thanks!

**Comment by bboozzoo** [comment]
Maybe I'm late here, but only access key is limited to 20 characters, secret is 40 characters. We're using pwgen to generate secret, access key is set to `mender-deployments`,

> We recommend using the `pwgen` utility for generating the **secret**

**Comment by maciejmrowiec** [comment]
we followed this tutorial yesterday and it did not work, needed to use 16 char secret

**Comment by bboozzoo** [comment]
I think you're confusing access key with secret, this is running just fine:

```
minio_1                 | Created minio configuration file at /root/.minio
minio_1                 | 
minio_1                 |  Minio is 85 days 15 hours 12 minutes old 
minio_1                 |  Update: docker pull minio/minio 
minio_1                 | 
minio_1                 | 
minio_1                 | Endpoint:  http://172.18.0.3:9000  http://127.0.0.1:9000
minio_1                 | AccessKey: minio 
minio_1                 | SecretKey: chai3eiPh2or5wee7GaeD5teidaaz4Qu  <-- 32 chars secret
minio_1                 | Region:    us-east-1
minio_1                 | SQS ARNs:  <none>
minio_1                 | 
```

**Comment by maciejmrowiec** [comment]
apparently we did then, thanks for double checking

**Pull request merged**
