### PR TITLE
Update artifact names for 1.4.0 release

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
Looks like we missed a few artifact name changes for 1.4.0.  Did I get this right?

**Comment by estenberg** [comment]
Yes, this looks like a correct change. However, this should have been done by automation, I think. Maybe @kacf can comment on why it did not automatically update?

**Comment by drewmoseley** [comment]
@estenberg I think the reason that particular invocation requires the leading '-' is that there was a previous command line parameter that used it; ie the '-C <dir>' option.  It definitely failed for me without it although a direct "tar xvf blah" does work.  I am cherry picking that back to older branches as well as to master.

**Comment by kacf** [comment]
> Yes, this looks like a correct change. However, this should have been done by automation, I think. Maybe @kacf can comment on why it did not automatically update?

No, that task is [still open](https://tracker.mender.io/browse/MEN-1140), I'm afraid. There has been talk of moving away from Grav, which would impact this a lot, so I haven't made a move here yet. @michaelatmender, any news on that?

**Comment by michaelatmender** [comment]
@kacf nothing specifically, just a general possibility that one day we'll move the docs. We should continue assuming we'll build the site with Grav for the medium-longish term future

**Comment by kacf** [comment]
Ok, I will act as if we stay with Grav then.

**Pull request merged**
