### PR TITLE
Hosted master sync

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by tranchitella** [comment]
@oleorhagen isn't this a duplicate of https://github.com/mendersoftware/mender-docs/pull/1784?

**Comment by oleorhagen** [comment]
> @oleorhagen isn't this a duplicate of #1784?

Yes, but with some fixups. I think you might have been a touch quick when merging. I just wanted a separate PR to run pipelines.

**Comment by oleorhagen** [comment]
Will have to re-enable the deb install test later.

**Comment by lluiscampos** [comment]
> Will have to re-enable the deb install test later.

Re-enabling at:

* https://github.com/mendersoftware/mender-docs/pull/1927

**Pull request merged**
