### PR TITLE
Feature deviceconnect: merged to master

### PR DESCRIPTION
**Pull request by merlin-northern**

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
I did a quick read through and I saw some minor things we can fix. At least fix the `mender-shell.conf` typo, everything else is optional.

Nice getting this finally in master!

**Comment by merlin-northern** [comment]
@lluiscampos : un million de gracias amigo. I am committing the critical one, and creating a new PR with the rest of the fixes.

**Comment by merlin-northern** [comment]
need to close this one due to the fact that I commited suggestion in github, which will fail our tests. all the corrections here: https://github.com/mendersoftware/mender-docs/pull/1261

**Comment by merlin-northern** [comment]
superseded by https://github.com/mendersoftware/mender-docs/pull/1262

**Pull request closed without merging**
