### PR TITLE
administration: notes on administration & deployment

### PR DESCRIPTION
**Pull request by bboozzoo**
@maciejmrowiec @mendersoftware/rndity @eysteins

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
This differs a little from the docs architecture plan: https://docs.google.com/document/d/1cFFiusOP8aErgcjnPgJG_0W4w2G0y7dIoZEDqBRl0nw/edit

However I find this split more intuitive than the one from google doc.

**Comment by bboozzoo** [comment]
There's a plan ;) ok, i'll check it out and update the PR.

**Comment by maciejmrowiec** [comment]
I favour your structure. @eysteins perhaps we can adjust the google doc plan?

**Comment by estenberg** [comment]
A few minor notes:

* Administration/Overview section is really good! Could have been merged immediately if it was a separate commit.

* Do you use https://github.com/mendersoftware/mender-docs-site? Several places have formatting issues with warning notes (e.g. "Make sure that the certificate matches the domain name..." is split so half of sentence only is warning-formatted).

**Comment by estenberg** [comment]
Regarding the main task (currently Administration/Deployments), it is currently too "bottom up" for the use case at hand (generate and use secure certificates everywhere). I do need to generate certs for all the services (which is in separate locations). I don't quite understand the current split. Do we need 3 different certificates (API Gateway, Minio, Token signing)? How do I generate them (only noted in Token signing)? Where do I put them on the machine that runs docker-compose (can be inferred by looking closely at the mount points)? Should I change the perms on them to make them strict? How do I make the client use the certs (it won't work otherwise)?

What I suggest for now:
* Remove Administration/Deployments for now, instead:
* Merge all the certificate generation and include everything (see notes above) into a tutorial-style separate section Administration/Certificates.
* Split out storage into it's own section Administration/Storage (currently two headers "Storage location" and "S3 storage backend"). Also include any storage limits here (max size per artifact? max artifacts?).
* Split out "Bandwidth and connection limiting" header into its own section Administration/Bandwidth.

I've updated the plan to include Storage as well, otherwise please try to follow that going forward to make sure everything is consistent: https://docs.google.com/a/cfengine.com/document/d/1cFFiusOP8aErgcjnPgJG_0W4w2G0y7dIoZEDqBRl0nw/edit?usp=sharing

**Comment by bboozzoo** [comment]
Ok, i"ll update the PR to be in line with documentation plan.

I'm not convinced about Administration/Bandwidth though. It gives the impression that this applies to the whole system while it's only storage download/connection limiting. We have no means of policing device/management requests.

**Comment by bboozzoo** [comment]
With current documentation plan, where do I put generating keys for token signing?

**Comment by bboozzoo** [comment]
I've updated the PR to be mostly in line with the documentation plan. The only divergence is 'Token sinign section', I did not have any idea where to put it, so it's become a seprate chapter.

**Comment by estenberg** [comment]
Thanks, I merged it and polished it a bit now.
It's available at https://docs.mender.io/Administration

I will continue to polish it - also see https://github.com/mendersoftware/integration/pull/113 and https://github.com/mendersoftware/mender-docs/pull/89.

**Comment by estenberg** [comment]
By the way, how come the deviceauth and useradm only have private keys? How are these shared between other services for verification? Or are the resulting signatures only verified by the services themselves?

**Comment by bboozzoo** [comment]
deviceauth and useradm need private keys to sign the tokens. Verification happens at the gateway, before forwarding the request to the upstream service nginx does an `auth_request` to either deviceauth or useradm (depending on the endpoint being accessed). Basically, the whole incoming request (sans the data obviously) gets forwarded to auth endpoint. Original headers are preserved (Authorization which carries token in our case) and 2 extra are added - X-Original-URI and X-Original-Method. When the request hits the upstream service eventually, it's already after auth verification.

**Comment by estenberg** [comment]
OK, thanks, I will include this in the docs.
So we could have used a MAC, such as HMAC-SHA256 instead of public key crypto for these services as well? Not that important now, but this will probably be quite a lot more efficient.

**Comment by bboozzoo** [comment]
Yes, we could have used HMAC but that requires you to use a shared secret. So for instance if a 3rd party wants to verify if token was issued by mender (not that there's a valid case for this atm), we'd need to have a public token verification service (we could not share the secret obviously). With RSA, we can just give them the public key.

**Pull request merged**
