### PR TITLE
[RFC] Update version to 1.1.0 from the beta.

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew.moseley@mender.io>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@estenberg this is my first attempt at this.  I'm not completely sure the cloudfront URLs are correct.  Please review

**Comment by drewmoseley** [comment]
To clarify, we currently have the following cloudfront.net URLs in the docs.

These have been updated and verified to exist:

1. https://d1b0l86ne08fsf.cloudfront.net/mender-artifact/2.0.0/mender-artifact
2. https://doyabzhx7xw8o.cloudfront.net/1.1.0/mender-standalone-1.1.0.tar.gz

These do not exist and it's unclear if these files have been uploaded somewhere or if it still needs to be done:

1. https://d1b0l86ne08fsf.cloudfront.net/1.1.0-build2/vexpress-qemu/vexpress_release_2_1.1.0-build2.mender
2. https://d1b0l86ne08fsf.cloudfront.net/1.1.0-build2/vexpress-qemu/vexpress_release_1_1.1.0-build2.mender
3. https://d1b0l86ne08fsf.cloudfront.net/1.1.0-build2/beaglebone/mender-beaglebone_1.1.0-build2.sdimg.gz
4. https://d1b0l86ne08fsf.cloudfront.net/1.1.0-build2/beaglebone/beaglebone_release_1_1.1.0-build2.mender

**Comment by estenberg** [comment]
@GregorioDiStefano @kacf can you please comment on above so we get the cloudfront URLs for all binaries?

**Comment by kacf** [comment]
@drewmoseley: All the links work as long as you replace `1.1.0-build2` with `1.1.0`. Build numbers never occur in final builds.

**Comment by drewmoseley** [comment]
OK. Thanks for the clarity.

I updated the URLs as @kacf described and verified that all cloudfront mentions in the docs are downloadable URLs.

@estenberg anything else?

**Comment by drewmoseley** [comment]
Oh yeah.  Screenshots.  I'll try to pull those in a bit.

**Comment by drewmoseley** [comment]
As near as I can tell, this is ready to go and satisfies all the checklist items with my name on them.

**Pull request merged**
